### ISSUE TITLE
Randomize AI controller

### ISSUE THREAD

**Issue by MarcusAromatorio** [MarcusAromatorio/AIGroupProject#6]
Randomize the selection of Agents to be updated, keeping track of flags for each so that no Agent gets skipped over

**Comment by dxt298** [comment]
Randomization can be done, but flagging takes up too many resources with high risk for infinite loop near the end of the randomization (when near everything has been flagged but a few have not).  

At this point, I'm going to leave them as is (looping in sequence), but I think it would be a better idea for them all to be doing their update simultaneously rather than one at a time.

**Comment by MarcusAromatorio** [comment]
I have to agree that having each agent update themselves simultaneously and independently would probably do better for the exercise. It won't be a difficult change by any means so I will tweak that.
